# index.html
<html>
<head>
<h1>La aventura de Luna por la Floresta</h1>
</head>
<body style="background-color:#DCC5E8">
<p>-En un reino encantado, donde los árboles susurraban secretos y las flores cantaban melodías, vivía una joven llamada Luna. Luna era una niña curiosa y aventurera, siempre ansiosa por explorar los misterios de la floresta. Un día, mientras paseaba por el bosque, se encontró con un pequeño duende llamado Brillo. Brillo era un duende travieso y juguetón, que siempre estaba dispuesto a ayudar a los demás. Luna y Brillo se hicieron amigos rápidamente y comenzaron a explorar juntos la floresta.Un día, mientras caminaban por un sendero oculto, se encontraron con un árbol antiguo y majestuoso. El árbol, llamado Árbol de la Sabiduría, era conocido por sus poderes mágicos. Luna y Brillo se acercaron al árbol y le pidieron que les revelara sus secretos. El árbol, con una voz suave y profunda, les dijo que la verdadera sabiduría se encontraba en la naturaleza y que debían aprender a escuchar y observar.</p>

<p1>Luna y Brillo siguieron los consejos del Árbol de la Sabiduría y comenzaron a prestar más atención a su entorno.Descubrieron que las flores hablaban con susurros suaves, que los árboles susurraban historias antiguas y que los animales tenían mensajes ocultos en sus cantos. Aprendieron a apreciar la belleza y la armonía de la naturaleza y a respetar a todas las criaturas que la habitaban. Las hadas, al ver a Luna y Brillo, les dieron la bienvenida y les invitaron a unirse a su baile. Luna y Brillo aceptaron con entusiasmo y comenzaron a bailar con las hadas. Se sintieron libres y felices, como si estuvieran flotando en el aire.Un día, mientras exploraban un claro en el bosque, Luna y Brillo se encontraron con un grupo de hadas que bailaban al ritmo de la música de los árboles. Las hadas, con sus alas brillantes y sus vestidos de colores, eran criaturas mágicas y hermosas. Luna y Brillo se quedaron maravillados por su danza y su alegría.Las hadas, al ver a Luna y Brillo, les dieron la bienvenida y les invitaron a unirse a su baile. Luna y Brillo aceptaron con entusiasmo y comenzaron a bailar con las hadas. Se sintieron libres y felices, como si estuvieran flotando en el aire.Cuando el baile terminó, las hadas se despidieron de Luna y Brillo y les agradecieron por haber respetado su hogar. Luna y Brillo se quedaron un momento en silencio, absorbiendo la magia del momento. Luego, se dieron la mano y se dirigieron hacia el camino de regreso a casa.</p1>

<p2>A partir de ese día, Luna y Brillo nunca volvieron a ser los mismos. Habían aprendido a apreciar la belleza y la magia de la naturaleza y a respetar a todas las criaturas que la habitaban. Habían descubierto que la verdadera sabiduría se encontraba en el corazón de la floresta y que la felicidad se encontraba en compartir la alegría con los demás.
Luna y Brillo siguieron los consejos del Árbol de la Sabiduría y comenzaron a prestar más atención a su entorno. Descubrieron que las flores hablaban con susurros suaves, que los árboles susurraban historias antiguas y que los animales tenían mensajes ocultos en sus cantos. Aprendieron a apreciar la belleza y la armonía de la naturaleza y a respetar a todas las criaturas que la habitaban.Un día, mientras exploraban un claro en el bosque, Luna y Brillo se encontraron con un grupo de hadas que bailaban al ritmo de la música de los árboles. Las hadas, con sus alas brillantes y sus vestidos de colores, eran criaturas mágicas y hermosas. Luna y Brillo se quedaron maravillados por su danza y su alegría.</p2>

<p3>Las hadas, al ver a Luna y Brillo, les dieron la bienvenida y les invitaron a unirse a su baile. Luna y Brillo aceptaron con entusiasmo y comenzaron a bailar con las hadas. Se sintieron libres y felices, como si estuvieran flotando en el aire.Cuando el baile terminó, las hadas se despidieron de Luna y Brillo y les agradecieron por haber respetado su hogar. Luna y Brillo se quedaron un momento en silencio, absorbiendo la magia del momento. Luego, se dieron la mano y se dirigieron hacia el camino de regreso a casa.A partir de ese día, Luna y Brillo nunca volvieron a ser los mismos. Habían aprendido a apreciar la belleza y la magia de la naturaleza y a respetar a todas las criaturas que la habitaban.</p3>


</body>
</html>
